# Generated by Django 4.0.5 on 2022-07-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='watches',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
