# Generated by Django 4.0.5 on 2022-07-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_recipe_watches'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time_to_cook',
            field=models.IntegerField(default=0),
        ),
    ]
